---

- name: 1 create nginx includes dir
  file:
    state: directory
    path: '{{ nginx_includes_dir }}'
    mode: og+wr
    owner: root
    group: root

- name: 2 NGINX OR includes config
  template:
    src: nginx_mw_include.j2
    dest: '{{ nginx_includes_dir }}/{{ nginx_conf }}'
    mode: og+wr
    owner: root
    group: root

- name: 3 remove comments from NGINX site default
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '#\s*?.*$'
    state: absent

- name: 4 insert mw conf to NGINX site default
  lineinfile:
    path: /etc/nginx/sites-available/default
    insertafter: 'root /var/www/html;'
    line: '        include {{ nginx_includes_dir }}/{{ nginx_conf }};'
    mode: og+wr
    owner: root
    group: root

- name: 5 insert index.php into index files
  replace:
    path: /etc/nginx/sites-available/default
    regexp: 'index\.nginx-debian\.html'
    replace: 'index.php'

- name: 6 enable NGINX default config
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: 7 reload_webserver
  service:
    name: 'nginx'
    state: reloaded
