---
mediawiki_path: '/var/www/html/wiki'  # IN DEPLOYMENT: overwrite in host file
mw_script_path: '/wiki'  # IN DEPLOYMENT: overwrite in host file
mw_instance_name: 'smwbox'  # IN DEPLOYMENT: overwrite in host file
mediawiki_language: 'en'
mediawiki_version: REL1_35
smw_version: '~3.2'
semanticscribunto_version: '~2.1'
semanticite_version: '~2.1'
semanticformats_version: '~3.2'
maps_version: '~9.0'

admin_user:
  name: Admin  # IN DEPLOYMENT: overwrite in host file
  pwd: AdminPassword  # IN DEPLOYMENT: overwrite in host file
mediawiki_db:
  connection: 'mysql'
  name: 'smwbox'  # IN DEPLOYMENT: overwrite in host file
  user: 'smwbox_db_user'  # IN DEPLOYMENT: overwrite in host file
  pwd: 'smwbox_db_user_pwd'  # IN DEPLOYMENT: overwrite in host file
