# vars values defined here roleX/defaults/main.yml are overwritten by inventory var values
# precedence (hightest 1st): -e "var=val", roleX/vars/main.yml, inventory, roleX/defaults/main.yml 
bin_dir: '/usr/local/bin'
src_dir: '/usr/local/src'
php_extensions:
  - "php-common"
  - "php-cli"
  - "php-fpm"
  - "php-pgsql"
  - "php-mysql"
  - "php-gd"
  - "php-bz2"
  - "php-zip"
  - "php-json"
  - "php-xml"
  - "php-curl"
  - "php-intl"
  - "php-mbstring"
  - "php-bcmath"
  - "php-soap"
  - "php-opcache"
  - "php-mail"
